joint_up_position_controller:
  type: position_controllers/JointPositionController
  joint: gripper_motor_up_joint
joint_down_position_controller:
  type: position_controllers/JointPositionController
  joint: gripper_motor_down_joint

joint_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gripper_motorup_joint
    - gripper_motordown_joint

joint_read_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0

#joint_read_command_controller:
#  type: joint_read_command_controller/JointReadCommandController 
#  publish_rate: 100.0


